# Use a lightweight Linux base image
FROM ubuntu:22.04

# Install required packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    openssh-client \
    git \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Install Ansible via pip
COPY ./ansible/requirements.txt .
RUN pip3 install -r requirements.txt

# Set up SSH directory for keys
RUN mkdir -p /root/.ssh
RUN chmod 700 /root/.ssh

# Expose a volume for SSH keys
VOLUME /root/.ssh

# Set working directory
WORKDIR /ansible

# This command keeps the container running indefinitely
CMD ["tail", "-f", "/dev/null"]
