---
- name: Test connectivity and gather facts
  hosts: targets
  tasks:
    - name: Ping all target hosts
      ansible.builtin.ping

    - name: Get OS info
      ansible.builtin.debug:
        msg: "The OS is {{ ansible_distribution }} {{ ansible_distribution_version }}"
