---
- name: Test connectivity and gather facts
  hosts: targets
  tasks:
    - name: Ping all target hosts
      ansible.builtin.ping

    - name: Get OS info
      # The `debug` module is correctly indented by two spaces.
      ansible.builtin.debug:
        # The `msg` parameter is correctly indented by two spaces under `debug`.
        msg: "The OS is {{ ansible_distribution }} {{ ansible_distribution_version }}"
